name: Deploy on changes

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check for frontend changes
      id: diff-frontend
      run: |
      if ! git diff --quiet ${{ github.event.before }} HEAD -- frontend/; then
        echo "::set-output name=has_changes::true"
      fi

    - name: Check for backend changes
      id: diff-backend
      run: |
      if ! git diff --quiet ${{ github.event.before }} HEAD -- backend/; then
        echo "::set-output name=has_changes::true"
      fi
      
    - name: Deploy frontend
      if: steps.diff-frontend.outputs.has_changes == 'true'
      run: |
        cd frontend && npm install --legacy-peer-deps && npm run build 
        aws s3 sync ./build s3://twitchstats.site/ --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"

    - name: Deploy backend
      if: steps.diff-backend.outputs.has_changes == 'true'
      run: |
        cd backend && npm install
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 913324685112.dkr.ecr.eu-west-1.amazonaws.com
        docker build -t twitch-stats .
        docker tag twitch-stats:latest 913324685112.dkr.ecr.eu-west-1.amazonaws.com/twitch-stats:latest
        docker push 913324685112.dkr.ecr.eu-west-1.amazonaws.com/twitch-stats:latest
        echo '${{ secrets.TASK_DEFINITION }}' > task-definition.json
        aws ecs register-task-definition --cli-input-json file://task-definition.json
        TASK_REVISION=$(aws ecs describe-task-definition --task-definition twitch-stats-task --query "taskDefinition.revision" --output text)
        aws ecs update-service --cluster twitch-stats --service twitch-stats-service-2 --task-definition twitch-stats-task:$TASK_REVISION